Add AGPL License
LightningCreations/passman pull request #2
Opened 2024-07-15 18:35 UTC by chorman0773

This proposes to apply the APGL v3+ License to the project.

2024-07-15 18:53 UTC, Suyashtnt approved these changes
LGTM

2024-07-15 18:54 UTC, kilbouri requested changes

2024-07-15 18:54 UTC, kilbouri commented on README.md
> +
Do we need two lines here?

2024-07-15 18:54 UTC, kilbouri commented on README.md
> +
Two lines?

2024-07-16 02:16 UTC, rdrpenguin04 approved these changes
I'll be honest, I wasn't onboard with AGPL at first, but I'm ok with it after hearing the rationale. The main reason is that AGPL will enforce either consistency or transparency between implementations.

2024-07-16 02:21 UTC, chorman0773 commented on README.md
> +
I like to have a blank line before and after a heading in markdown.

2024-07-16 02:22 UTC, kilbouri commented on README.md
> +
Yes, _a_ blank line. There are two. I never remember to select the lines I care about when adding comments, that's on me.

2024-07-16 02:46 UTC, kilbouri approved these changes

2024-07-16 02:47 UTC, merged